
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'my_new_project'
version: '1.0.0'
config-version: 2
dbt-cloud:
    project-id: 70437463662430

# This setting configures which "profile" dbt uses for this project.
profile: 'analytics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# ============================================================================
# POV Model Cost Calculator Configuration
# https://github.com/dbt-labs/dbt-pov-model-cost-calculator
# ============================================================================

# Add the package query comment to your existing dbt_project.yml query comment
query-comment: "{{ dbt_pov_model_cost_calculator.query_comment(node) }}"


vars:
 dbt_pov_model_cost_calculator:
   # Optional: restrict reporting window to recent runs
   model_monitor_start_date: '2026-01-25'
   # Optional: Customize schema where the tracking tables will be created
   artifact_schema: "pov_model_cost_tracking"

models:
  # Materialize all project models as tables
  my_new_project:
    +materialized: table
  # Keep the package's outputs (fct_*/rpt_*) in a clean, separate schema
  dbt_pov_model_cost_calculator:
    +schema: pov_model_cost_calculator